version: "3.7"
services:
  penr-oz-covid19-forecaster:
    image: penr-oz-covid19-forecaster
    container_name: penr-oz-covid19-forecaster
    build: .
    ports:
    - "5000:5000"
    working_dir: /code
    volumes:
    - ./src/:/code/
    - .cache:/root/.cache
    entrypoint: python
    command: app.py
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_ENV: development
    healthcheck:
      test: wget -q --spider -t 1 http://localhost:5000/liveness || exit 1
      interval: 30s
      timeout: 10s
      retries: 3