apiVersion: apps/v1
kind: Deployment
metadata:
  name: penroz-covid19-forecaster
  labels:
    app: penroz-covid19-forecaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penroz-covid19-forecaster
  template:
    metadata:
      labels:
        app: penroz-covid19-forecaster
    spec:
      containers:
        - name: penroz-covid19-forecaster
          image: ozguramac/penr-oz-covid19-forecaster
          ports:
            - containerPort: 8000
          workingDir: /code
          command: ["gunicorn"]
          args: ["app:app"]
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: FLASK_ENV
              value: "production"
            - name: GUNICORN_CMD_ARGS
              value: "--bind=0.0.0.0"
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: penroz-covid19-forecaster
spec:
  selector:
    app: penroz-covid19-forecaster
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: penroz-covid19-forecaster
  labels:
    app: penroz-covid19-forecaster
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Environment=main, Project=penroz
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect",
      "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    external-dns.alpha.kubernetes.io/hostname: covid19.eks.derinworksllc.com
spec:
  rules:
    - host: covid19.eks.derinworksllc.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: penroz-covid19-forecaster
              servicePort: 8000